os:
  - linux
dist: xenial
language: dart
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone --depth 1 --single-branch https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - cd packages/core
script:
  - ../../flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
after_success:
  - bash <(curl -s https://codecov.io/bash)
