os:
  - linux
dist: focal
language: dart

services:
  - postgresql
addons:
  postgresql: "12.2"
  chrome: stable
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
      - postgresql-12
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - PGHOST=localhost
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - postgres --version
before_script:
  - git clone --depth 1 --single-branch https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - psql -c 'create database test_db;' -U postgres
script:
  - cd $TRAVIS_BUILD_DIR/packages/core && ../../flutter/bin/flutter test
  - cd $TRAVIS_BUILD_DIR/packages/api_commons && ../../flutter/bin/dart test
  - cd $TRAVIS_BUILD_DIR/packages/commons && ../../flutter/bin/dart test
cache:
  directories:
    - $HOME/.pub-cache
after_success:
  - bash <(curl -s https://codecov.io/bash)
