name: butter

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  prepare: melos bootstrap

  analyze:
    run: dart analyze --fatal-infos --fatal-warnings .

  test_all:
    run: melos bootstrap && melos analyze && melos butter_test && melos butter_ui_test &&
      melos butter_api_commons_test && melos butter_commons_test && 
      melos butter_cli_test

  sync_versions:
    description: Synchronize the versions of all packages to match the root package version.
    run: |
      ROOT_VERSION=$(melos list --scope="butter" --json | jq -r ".[0].version")
      melos exec "sed -i \"\" \"s/version: .*/version: $ROOT_VERSION/\" pubspec.yaml"
      melos version --no-git-tag-version --yes

  butter_test:
    run: cd $MELOS_ROOT_PATH/packages/core && flutter test --coverage
    select-package:
      scope: butter
      dir-exists: test
  
  butter_ui_test:
    run: cd $MELOS_ROOT_PATH/packages/ui_toolkit && flutter test --coverage
    select-package:
      scope: butter_toolkit
      dir-exists: test

  butter_api_commons_test:
    run: cd $MELOS_ROOT_PATH/packages/api_commons/example/sample_api && dart test --coverage=./coverage
    select-package:
      scope: butter_api_commons
      dir-exists: test

  butter_commons_test:
    run: cd $MELOS_ROOT_PATH/packages/commons && dart test --coverage=./coverage
    select-package:
      scope: butter_commons
      dir-exists: test

  butter_cli_test:
    run: cd $MELOS_ROOT_PATH/packages/cli && dart test --coverage=./coverage
    select-package:
      scope: butter_cli
      dir-exists: test

ide:
  intellij: false
