name: sample_api
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  butter_api_commons:
    git: 
      url: https://github.com/kbaylosis/butter.git
      ref: conduit_4.2.1-rc.1
      path: packages/api_commons
  conduit_core: #^4.2.0
    git:
      url: https://github.com/kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/core

dev_dependencies:
  conduit_test: #^4.2.0
    git: 
      url: https://github.com/kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/test_harness
  faker: ^2.1.0
  test: ^1.21.6
