name: sample_api
description: An empty conduit application.
version: 2.4.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  butter_api_commons:
    path: ../..
  conduit: ^4.3.9

dev_dependencies:
  conduit_test: ^4.3.7
  faker: ^2.1.0
  test: ^1.21.6
