name: sample_api
description: An empty conduit application.
version: 2.5.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  butter_api_commons:
    path: ../..
  conduit: ^4.4.0

dev_dependencies:
  conduit_test: ^5.0.0
  faker: ^2.1.0
  test: ^1.25.2
