name: butter_commons
description: Common utilities for butter systems
version: 2.6.0
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/commons

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  intl: ^0.19.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.25.2
  ulid: ^2.0.0
