name: butter_commons
description: Common utilities for butter systems
version: 2.0.1
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/commons

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  ulid: ^2.0.0
