name: butter_toolkit
description: UI toolkit for butter projects
version: 2.5.0
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/ui_toolkit

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  avoid_keyboard: ^0.3.0
  butter: ^2.5.0
  collection: ^1.16.0
  country_pickers: ^2.0.0
  flutter:
    sdk: flutter
  flutter_vector_icons: ^2.0.0
  intl: ^0.18.0
  moor: ^4.6.1+1
  moor_flutter: ^4.1.0
  package_info_plus: ^5.0.1
  rive: ^0.12.4
  sqlite3_flutter_libs: ^0.5.10
  throttling: ^1.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  moor_generator: ^4.6.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
