name: butter_api_commons
description: Common API Utilities for butter systems
version: 2.1.4
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/api_commons
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  butter_commons: ^2.0.5
  collection: ^1.17.0
  # conduit: #^4.2.0
  conduit_common: #^4.2.0
    git: 
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/common
  conduit_core: #^4.2.0
    git: 
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/core
  conduit_open_api: #^4.2.0
    git: 
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/open_api
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  conduit_test: #^4.2.0
    git: 
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/test_harness
  faker: ^2.1.0
  lints: ^2.0.0
  test: ^1.22.0
