name: butter_api_commons
description: Common API Utilities for butter systems
version: 2.2.3
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/api_commons

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  butter_commons: ^2.1.0
  collection: ^1.17.0
  conduit: ^4.2.2
  conduit_common: ^4.2.2
  conduit_core: ^4.2.2
  conduit_open_api: ^4.2.2
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  conduit_test: ^4.2.2
  faker: ^2.1.0
  lints: ^2.0.0
  test: ^1.22.0
