name: butter_api_commons
description: Common API Utilities for Butter systems
version: 0.0.1+1
publish_to: none
homepage: https://zoogtech.com
repository: https://github.com/kbaylosis/butter_api_commons

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  butter_commons:
    path: ../commons
  conduit: 4.0.0
  conduit_common: 4.0.0
  conduit_open_api: 4.0.0
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  conduit_test: 4.0.0
  faker: ^2.1.0
  lints: ^2.0.0
  test: ^1.22.0
