name: butter_api_commons
description: Common API Utilities for butter systems
version: 2.6.0
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/api_commons

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  butter_commons: ^2.6.0
  collection: ^1.18.0
  conduit: ^4.4.0
  conduit_common: ^4.4.0
  conduit_core: ^4.4.0
  conduit_open_api: ^4.4.0
  conduit_postgresql: ^4.4.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  conduit_test: ^5.0.0
  faker: ^2.1.0
  lints: ^2.0.0
  test: ^1.25.2
