name: butter_api_commons
description: Common API Utilities for butter systems
version: 2.5.0
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/api_commons

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  butter_commons: ^2.5.0
  collection: ^1.17.0
  conduit: ^4.3.9
  conduit_common: ^4.3.7
  conduit_core: ^4.3.8
  conduit_open_api: ^4.3.7
  conduit_postgresql: ^4.3.7
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  conduit_test: ^4.3.7
  faker: ^2.1.0
  lints: ^2.0.0
  test: ^1.22.0
