name: butter_cli
description: The cli companion of the butter framework. This tool is used to generate the project scaffolding.
version: 2.5.0
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/cli

environment:
  sdk: '>=3.3.0 <4.0.0'

executables:
  butter_cli:

dependencies:
  path: ^1.8.3
  args: ^2.3.1
  io: ^1.0.3
  mustache_template: ^2.0.0
  recase: ^4.1.0
  pub_cache: ^0.3.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.22.1
  test_process: ^2.0.3
